### ISSUE TITLE
CORS policy fehler

### ISSUE THREAD

**Issue by sebifyy** [JirkaDellOro/EIA2-Inverted#275]
Hi!

Habe ein Problem mit der Kommunikation zu Heroku.

Habe meinen Code per Localhost getestet und implementiert, aber sobald ich statt dem Localhost durch eine Verbindung zu Heroku ersetze, geht vieles schief.
Mein Canvas wird nicht mehr dargestellt (obwohl im HTML Dokument vorhanden), auch die Feuerwerk Raketen funktionieren dann nicht mehr.

Das hier ist die Fehlerausgabe in der console
![image](https://user-images.githubusercontent.com/43846468/107835293-416cb800-6d99-11eb-9edc-555103679635.png)

Und hier die Ausgabe im Heroku Log
`2021-02-13T00:18:43.000000+00:00 app[api]: Build succeeded
2021-02-13T00:18:45.733545+00:00 heroku[web.1]: Starting process with command `npm start`
2021-02-13T00:18:48.661262+00:00 app[web.1]: 
2021-02-13T00:18:48.661281+00:00 app[web.1]: > eia2-endabgabe-sh@1.0.0 start /app
2021-02-13T00:18:48.661282+00:00 app[web.1]: > node Server/Server.js remote
2021-02-13T00:18:48.661282+00:00 app[web.1]: 
2021-02-13T00:18:49.032537+00:00 app[web.1]: Server startet auf Port 44660
2021-02-13T00:18:49.044903+00:00 app[web.1]: (node:21) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
2021-02-13T00:18:49.044926+00:00 app[web.1]: (Use `node --trace-warnings ...` to show where the warning was created)
2021-02-13T00:18:49.121181+00:00 heroku[web.1]: State changed from starting to up
2021-02-13T00:19:19.130859+00:00 app[web.1]: (node:21) UnhandledPromiseRejectionWarning: MongoServerSelectionError: connection <monitor> to 18.193.155.142:27017 closed
2021-02-13T00:19:19.130868+00:00 app[web.1]:     at Timeout._onTimeout (/app/node_modules/mongodb/lib/core/sdam/topology.js:438:30)
2021-02-13T00:19:19.130869+00:00 app[web.1]:     at listOnTimeout (internal/timers.js:554:17)
2021-02-13T00:19:19.130870+00:00 app[web.1]:     at processTimers (internal/timers.js:497:7)
2021-02-13T00:19:19.131013+00:00 app[web.1]: (node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2021-02-13T00:19:19.131098+00:00 app[web.1]: (node:21) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by JirkaDellOro** [comment]
Schicke bitte Links zu Code und App

**Comment by sebifyy** [comment]
Hier ist mein Repository
https://github.com/sebifyy/EIA2_Endabgabe-SebastianHoffmann

Und hier die Server.ts Datei
https://github.com/sebifyy/EIA2_Endabgabe-SebastianHoffmann/blob/master/Server/Server.ts

Heroku-App
https://eia2-endabgabe-sh.herokuapp.com/

**Comment by JirkaDellOro** [comment]
@Sahertia (https://github.com/Sahertia)

hatte möglicherweise vorhin ein vergleichbares Problem. Er schrieb: Hauptproblem gelöst: network settings des MongoDB Cluster > allow access from everywhere

Probier' mal aus bzw. hake bei Rouven nach

**Comment by sebifyy** [comment]
Der Fehler wäre beseitigt, die Connection zur Datenbank steht jetzt. Jedoch stoß ich auf ein weiteres Problem:
![image](https://user-images.githubusercontent.com/43846468/107942443-88ba9a80-6f8b-11eb-88f1-f4f3480eaac4.png)

**Comment by sebifyy** [comment]
Problem gelöst!
Der Fehler war, dass ich bei dem Link zu meiner Herokuapp nicht "https://..." eingefügt habe. Jetzt funktioniert wieder alles wie gedacht
